### PR TITLE
Fix for issue #680

### PR DESCRIPTION
**Pull request by imran-ansari**

### CODE REVIEW

**Comment by imran-ansari** [comment]
@wdurairaj , @nilangekarss , please review the changes

**Comment by nilangekarss** [comment]
@imran-ansari I am okay with this changes if basic testing for default volume creation is done .
Code looks fine for me.

**Comment by imran-ansari** [comment]
> @imran-ansari I am okay with this changes if basic testing for default volume creation is done .
> Code looks fine for me.

Tested basic CRD, mount, unmount, operations along with invalid CPG TC

**Comment by wdurairaj** [comment]
Pending review comment is on the UT which can be addressed in different PR. Considering this is the going in a final RC build. Merging.

**Pull request merged**
