### PR TITLE
Fix for lost volume mounts after node reboot

### PR DESCRIPTION
**Pull request by kfeh**
This Pull Request resolves our Issue #641 
We tested this fix on serveral hosts and the issue is resolved!

We fixed the issue in the braches plugin_v2 and v300. If the fix should be applied to other branches, please do this on your own.

### CODE REVIEW

**Comment by wdurairaj** [comment]
there are UT and pep8 failures as shown in the travis ci build. Request @kfeh to investigate and fix this.

**Comment by kfeh** [comment]
What do you mean by UT failures?

**Comment by wdurairaj** [comment]
@kfeh , UT -> unit tests  check this log https://travis-ci.com/hpe-storage/python-hpedockerplugin/builds/115421688 available in the third tab of this pull request page.

**Comment by kfeh** [comment]
Pep8 is fixed.
Unit Tests is a bit strange... I just copied the code of a exisiting method "mount_dir" and reused it including the exception-handling. So there cannot be any error on the new method...
Do you know what is meant by:
('hpeplugin_driver do_setup failed, error is: %s', 'catching classes that do not inherit from BaseException is not allowed')

**Comment by kfeh** [comment]
Ok, Build is now green!

**Pull request merged**
