### PR TITLE
Fix for lost volume mounts after node reboot 

### PR DESCRIPTION
**Pull request by kfeh**
This Pull Request resolves our Issue #641 
We tested this fix on serveral hosts and the issue is resolved!

We fixed the issue in the braches plugin_v2 and v300. If the fix should be applied to other branches, please do this on your own.

### CODE REVIEW

**Comment by wdurairaj** [comment]
there are UT and pep8 failures as shown in the travis ci build. Request @kfeh to investigate and fix this.

**Comment by kfeh** [comment]
What do you mean by UT failures?

**Comment by kfeh** [comment]
Ok, Build is now green!

**Comment by wdurairaj** [comment]
This change caused regression on plugin_v2 branch and there was a PR done by me -- https://github.com/hpe-storage/python-hpedockerplugin/pull/674 . Fix was released as part of 3.2 tag already, and hence no action will taken on this PR for v300 branch.

**Comment by wdurairaj** [comment]
This was the original change for the regression fix -- https://github.com/hpe-storage/python-hpedockerplugin/pull/673/files

**Pull request closed without merging**
